import {chromium} from 'playwright';import {rmSync} from 'node:fs';
// Start from the demo's default composition (the editor autosaves components per scenario).
const resetDemo=()=>{for(const f of ['spaces/demo/scenarios/demo/composition.json','spaces/demo/scenarios/demo/assets'])rmSync(new URL('../'+f,import.meta.url),{recursive:true,force:true});};resetDemo();import assert from 'node:assert/strict';
const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--use-angle=swiftshader','--enable-webgl']});
try{const p=await b.newPage({viewport:{width:1280,height:950}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8766');await p.waitForFunction(()=>window.replay?.ready);await p.evaluate(()=>window.replay.setFrame(30));assert.equal(await p.locator('#time').textContent(),'2.00 s');await p.locator('#x').fill('0.2');assert.equal(await p.evaluate(()=>window.replay.anchor.position.x),.2);await p.locator('#visible').uncheck();assert.equal(await p.evaluate(()=>window.replay.anchor.visible),false);await p.locator('#visible').check();
await p.evaluate(async()=>{const THREE=await import('three');const {GLTFExporter}=await import('three/addons/exporters/GLTFExporter.js');const m=new THREE.Mesh(new THREE.SphereGeometry(.2),new THREE.MeshStandardMaterial({color:0x99ddcc}));m.position.y=.2;const data=await new GLTFExporter().parseAsync(m,{binary:true});await window.replay.loadGLB(new File([data],'test-sphere.glb'),false);});await p.waitForFunction(()=>(r=>r.components.get(r.selected).spec)(window.replay).name==='test-sphere.glb');
const saved=await p.evaluate(()=>window.replay.placement());assert.ok(/^(data:|assets\/)/.test(saved.components.find(c=>c.id===saved.selected).src));await p.evaluate(async saved=>{await window.replay.loadPlacement(saved);await window.replay.setFrame(70);},saved);assert.equal(await p.evaluate(()=>(r=>r.components.get(r.selected).spec)(window.replay).name),'test-sphere.glb');
// Only the sphere from here on (the cube would cast its own shadow).
await p.evaluate(()=>{const r=window.replay,cube=r.components.instances.find(i=>i.spec.component==='calibration-cube');r.components.remove(cube.spec.id);r.select(r.components.instances[0].spec.id);});
// Test a room GLB through the actual file-input route and depth mode.
await p.evaluate(async()=>{const THREE=await import('three');const {GLTFExporter}=await import('three/addons/exporters/GLTFExporter.js');const m=new THREE.Mesh(new THREE.BoxGeometry(2,.1,2),new THREE.MeshBasicMaterial());m.position.set(0,0,-2.5);const data=await new GLTFExporter().parseAsync(m,{binary:true});await window.replay.loadGLB(new File([data],'test-room.glb'),true);});await p.waitForFunction(()=>window.replay.placement().room==='test-room.glb');await p.evaluate(([id,on])=>{const c=document.getElementById(id);c.checked=on;c.dispatchEvent(new Event('change'));},['occlude',true]);assert.equal(await p.evaluate(()=>window.replay.placement().occlude),true);await p.evaluate(([id,on])=>{const c=document.getElementById(id);c.checked=on;c.dispatchEvent(new Event('change'));},['occlude',false]);
// LiDAR depth occlusion: the demo has exact depth (wall at z=-6). An object behind the wall must vanish; in front of it, stay.
const stage=()=>p.locator('#stage').screenshot();await p.evaluate(()=>window.replay.setFrame(30));await p.evaluate(()=>window.replay.applyPlacement({version:1,position:[0,.5,-7],scale:1,yaw:0,visible:true}));
await p.evaluate(([id,on])=>{const c=document.getElementById(id);c.checked=on;c.dispatchEvent(new Event('change'));},['depth-occlude',false]);const behind=await stage();await p.locator('#visible').uncheck();const empty=await stage();await p.locator('#visible').check();
assert.notDeepEqual(behind,empty,'Without occlusion the object behind the wall is drawn');
assert.equal(await p.locator('#depth-occlude').isDisabled(),false);await p.evaluate(([id,on])=>{const c=document.getElementById(id);c.checked=on;c.dispatchEvent(new Event('change'));},['depth-occlude',true]);await p.waitForFunction(()=>window.replay.placement().depthOcclude);
assert.deepEqual(await stage(),empty,'Depth occlusion hides an object behind the wall');
await p.evaluate(()=>window.replay.applyPlacement({version:1,position:[0,0,-2.5],scale:1,yaw:0,visible:true}));assert.notDeepEqual(await stage(),empty,'An object in front of the wall stays visible');
// Shadows: the floor-standing object darkens the real floor next to it; nothing changes when the object is hidden.
const shade=async on=>{await p.evaluate(on=>{const c=document.getElementById('shadows');c.checked=on;c.dispatchEvent(new Event('change'));},on);return p.locator('#stage').screenshot();};
assert.notDeepEqual(await shade(true),await shade(false),'Shadow is drawn');
await p.locator('#visible').uncheck();assert.deepEqual(await shade(true),await shade(false),'No shadow without the object');await p.locator('#visible').check();
// Keyboard: arrows step frames, Shift+arrow one second, Space toggles playback.
await p.locator('#time').click();await p.keyboard.press('ArrowRight');await p.waitForFunction(t=>document.getElementById('time').textContent===t,'2.07 s',{timeout:3000});
await p.keyboard.press('Shift+ArrowLeft');await p.waitForFunction(t=>document.getElementById('time').textContent===t,'1.07 s',{timeout:3000});
await p.keyboard.press('Space');assert.equal(await p.locator('#play').getAttribute('aria-label'),'Pause');await p.keyboard.press('Space');assert.equal(await p.locator('#play').getAttribute('aria-label'),'Play');
resetDemo();assert.deepEqual(errors,[]);console.log('PASS: load, scrub, placement, visibility, GLB, embedded round-trip, room occlusion, LiDAR depth occlusion, shadows, keyboard; no page errors');
}finally{await b.close();}
